export function fetchData(){
    let returnArray = [
        {name: "all", url: "all", images: ["https://storage.googleapis.com/2022fundraising-website/3638/south","https://storage.googleapis.com/2022fundraising-website/539blossom/south","https://storage.googleapis.com/2022fundraising-website/825/south","https://storage.googleapis.com/2022fundraising-website/61castro/south"]},
        {name: "36 38 castro", url:"3638castro", images:["https://storage.googleapis.com/2022fundraising-website/3638/south","https://storage.googleapis.com/2022fundraising-website/3638/floor","https://storage.googleapis.com/2022fundraising-website/3638/east","https://storage.googleapis.com/2022fundraising-website/3638/west","https://storage.googleapis.com/2022fundraising-website/3638/north"] },
        {name: "539 blossom", url:"539blossom", images:["https://storage.googleapis.com/2022fundraising-website/539blossom/south","https://storage.googleapis.com/2022fundraising-website/539blossom/floor","https://storage.googleapis.com/2022fundraising-website/539blossom/east","https://storage.googleapis.com/2022fundraising-website/539blossom/west","https://storage.googleapis.com/2022fundraising-website/539blossom/north"], downloadPDF:"https://storage.googleapis.com/dsffd/28.jpg"},
        {name: "817 825 rodney", url:"817825rodney", images: ["https://storage.googleapis.com/2022fundraising-website/825/south","https://storage.googleapis.com/2022fundraising-website/825/floor","https://storage.googleapis.com/2022fundraising-website/825/east","https://storage.googleapis.com/2022fundraising-website/825/west","https://storage.googleapis.com/2022fundraising-website/825/north",]},
        {name: "61 castro", url: "61castro", images: ["https://storage.googleapis.com/2022fundraising-website/61castro/south","https://storage.googleapis.com/2022fundraising-website/61castro/floor","https://storage.googleapis.com/2022fundraising-website/61castro/east","https://storage.googleapis.com/2022fundraising-website/61castro/west","https://storage.googleapis.com/2022fundraising-website/61castro/north"], downloadPDF:"https://storage.googleapis.com/dsffd/33.jpg"}

    ]
    return returnArray
}